version: "3"
services:
  webrtc_front:
    depends_on:
    - webrtc_back
    image: omwalid/webrtcapp_front:v1.1.5
    container_name: webrtc_front
    ports:
    - 8000:80
  
  webrtc_back:
    image: omwalid/webrtcapp_back:v1.2
    container_name: webrtc_back
    ports:
    - 5000:5000